### ISSUE TITLE
ISO 8601 date format

### ISSUE THREAD

**Issue by ilyannn** [krzysztofzablocki/KZPropertyMapper#49]
Just wanted to let you know that [ISO 8601](https://en.wikipedia.org/?title=ISO_8601) is a rather complicated format and it's not easy to catch all of its possibilities with `NSDateFormatter`: for example, both `2015-07-01` and `2015-07-01T00:00:00` are allowed, but aren't parsed by current implementation.
 
It was very easy to combine [iso-8601-date-formatter](https://github.com/boredzo/iso-8601-date-formatter) with `KZPropertyMapper`, but perhaps it should be used by default.

**Comment by krzysztofzablocki** [comment]
@ilyannn Yeah I know, but I don't want to add extra dependency, it's very straighforward to add any kind of boxing to kzpm
