### ISSUE TITLE
Suppressing error messages

### ISSUE THREAD

**Issue by crtlabs** [krzysztofzablocki/KZPropertyMapper#57]
Is it possible, to somehow disable warnings like:
<code>
KZPropertyMapper: Ignoring mapping from matchTime to matchTime because type (null) does NOT match NSString
</code>

I'm avare that this might be null, NSString out of null is empty. I'm ready for that, but it just overflows my log and would not like to see it.

**Comment by crtlabs** [comment]
Krzysztof, bump:) Da sie coś z tym zrobić?

**Comment by krzysztofzablocki** [comment]
did you try `[KZPropertyMapper logIgnoredValues: YES]` ?

**Comment by crtlabs** [comment]
That's great!

But is there any possibility to limit it per property/single mapping dictionary?

**Comment by krzysztofzablocki** [comment]
it's a function so you can call it before / after mapping, not on per property basis but on per dict basis it would work. That is assuming you aren't running multiple ones in parallel, if you wanted to have it work in parallel you could send me a PR that could add the ignore configuration into the mapping method itself.
