### ISSUE TITLE
Crash when converting from number to NSDate

### ISSUE THREAD

**Issue by iulukaya** [krzysztofzablocki/KZPropertyMapper#58]
mapping is @"timestamp": KZBox(Date, postDate)
it works when timestamp is string, but not when it's a number

**Comment by krzysztofzablocki** [comment]
the built-in boxing for date requires a string of standard format, not timestamp.
You need to provide your own boxing for those kind of data, this should help: https://github.com/krzysztofzablocki/KZPropertyMapper#expanding-boxing-capabilities

**Comment by iulukaya** [comment]
thanks!
